---
- hosts: 02-aio
  sudo: yes
  tasks:
    - include: tasks/base.yml
      vars:
        systemd_docker_config_directory: /etc/systemd/system/docker.service.d
        pypi_packages:
          - ansible
          - docker
          - kolla-ansible
          - python-openstackclient
        rpm_packages:
          - docker-ce
          - python-devel
          - python-pip
          - ca-certificates
          - gcc
          - libffi-devel
          - openssl
          - libselinux-python
          - ntp
    - include: tasks/ssh.yml
    - include: tasks/conf.yml
      vars:
        network_interface:          enp0s8
        neutron_external_interface: enp0s9
        kolla_internal_vip_address: "{{ '.'.join(vars['ansible_' + vars['network_interface']]['ipv4']['address'].split('.')[:3] + ['222']) }}"
        external_ip: "{{ '.'.join(vars['ansible_' + vars['neutron_external_interface']]['ipv4']['address'].split('.')[:3]) }}"
        ext_net_cidr:    "{{ external_ip }}.0/24"
        ext_net_range:   "start={{ external_ip }}.100,end={{ external_ip }}.200"
        ext_net_gateway: "{{ external_ip }}.1"
        config_files:
          - { src: "tasks/config", dest: "/etc/systemd/system/docker.service.d", file: "kolla.conf"}
          - { src: "tasks/config", dest: "/root/inventory",                      file: "all-in-one"}
          - { src: "tasks/config", dest: "/etc",                                 file: "hosts"}
          - { src: "tasks/config", dest: "/etc/kolla/config",                    file: "ceph.conf"} # only all-in-one need this
    - name: Prepare the OSD as storage driver
      shell: |
        parted /dev/sdb -s -- mklabel gpt mkpart KOLLA_CEPH_OSD_BOOTSTRAP 1 -1
      ignore_errors: yes        # may already in use
    - name: Clean old containers
      shell: |
        docker stop `docker ps -a -q`
        docker system prune --force
        /usr/share/kolla-ansible/tools/cleanup-host
        /usr/share/kolla-ansible/tools/cleanup-containers
    - name: Deploy all the instance
      shell: |
        kolla-ansible deploy -i /root/inventory/all-in-one
        kolla-ansible post-deploy
    - name: Create the All In One Kolla
      shell: |
        source /etc/kolla/admin-openrc.sh
        /usr/share/kolla-ansible/init-runonce
    - name: Make the br-ex had a new ip address, it connects br-ex
      shell: |
        ip addr add 10.0.24.254/24 dev br-ex
        ip link set br-ex up
