---
- hosts: 03-multinode
  sudo: yes
  tasks:
    - include: tasks/base.yml
      vars:
        systemd_docker_config_directory: /etc/systemd/system/docker.service.d
        pypi_packages:
          - ansible
          - docker
          - kolla-ansible
          - python-openstackclient
        rpm_packages:
          - docker-ce
          - python-devel
          - python-pip
          - ca-certificates
          - gcc
          - libffi-devel
          - openssl
          - libselinux-python
          - ntp
    - include: tasks/conf.yml
      vars:
        network_interface:          enp0s8
        neutron_external_interface: enp0s9
        kolla_internal_vip_address: "{{ '.'.join(vars['ansible_' + vars['network_interface']]['ipv4']['address'].split('.')[:3] + ['222']) }}"
        external_ip: "{{ '.'.join(vars['ansible_' + vars['neutron_external_interface']]['ipv4']['address'].split('.')[:3]) }}"
        ext_net_cidr:    "{{ external_ip }}.0/24"
        ext_net_range:   "start={{ external_ip }}.100,end={{ external_ip }}.200"
        ext_net_gateway: "{{ external_ip }}.1"
      when: ansible_hostname | search("deploy")
    - name: Prepare the OSD as storage driver
      shell: |
        parted /dev/sdb -s -- mklabel gpt mkpart KOLLA_CEPH_OSD_BOOTSTRAP 1 -1
      when: ansible_hostname | search("storage")
