---
- hosts: 03-multinode
  sudo: yes
  tasks:
    - include: tasks/base.yml
      vars:
        systemd_docker_config_directory: /etc/systemd/system/docker.service.d
        pypi_packages:
          - ansible
          - docker
          - kolla-ansible
          - python-openstackclient
        rpm_packages:
          - docker-ce
          - python-devel
          - python-pip
          - ca-certificates
          - gcc
          - libffi-devel
          - openssl
          - libselinux-python
          - ntp
    - include: tasks/conf.yml
      vars:
        network_interface:          enp0s8
        neutron_external_interface: enp0s9
        kolla_internal_vip_address: "{{ '.'.join(vars['ansible_' + vars['network_interface']]['ipv4']['address'].split('.')[:3] + ['222']) }}"
        external_ip: "{{ '.'.join(vars['ansible_' + vars['neutron_external_interface']]['ipv4']['address'].split('.')[:3]) }}"
        ext_net_cidr:    "{{ external_ip }}.0/24"
        ext_net_range:   "start={{ external_ip }}.100,end={{ external_ip }}.200"
        ext_net_gateway: "{{ external_ip }}.1"
      when: ansible_hostname | search("deploy")
    - name: Get contents from /usr/share/kolla-ansible
      copy:
        src: tasks/config/multinode
        dest: /root/inventory/multinode
        force: yes
      when: ansible_hostname | search("deploy")
    - name: Prepare the OSD as storage driver
      shell: |
        parted /dev/sdb -s -- mklabel gpt mkpart KOLLA_CEPH_OSD_BOOTSTRAP 1 -1
      when: ansible_hostname | search("storage")
      ignore_errors: yes        # may already in use
    - name: This process should NOT takes long, otherwise set host_key_checking = False in ansible.cfg
      shell: |
        ansible all -i multinode -a "hostname"
    - name: Deploy the multinode on deployment-1 machine
      shell: |
        kolla-ansible deploy -i /root/inventory/multinode
        kolla-ansible post-deploy -i /root/inventory/multinode
      when: ansible_hostname | search("deploy-1")
    - name: Create new instance
      shell: |
        source /etc/kolla/admin-openrc.sh
        /usr/share/kolla-ansible/init-runonce
      when: ansible_hostname | search("deploy-1")
    - name: Make the br-ex had a new ip address, it connects br-ex
      shell: |
        ip addr add 10.0.26.254/24 dev br-ex
        ip link set br-ex up
      when: ansible_hostname | search("network")
