---
- hosts: 02-aio
  sudo: yes
  tasks:
    - name: Make sure the root ssh folder exists
      file:
        path: /root/.ssh
        state: directory
    - include: tasks/base.yml
      vars:
        systemd_docker_config_directory: /etc/systemd/system/docker.service.d
        pypi_packages:
          - ansible
          - docker
          - kolla-ansible
          - python-openstackclient
        rpm_packages:
          - docker-ce
          - python-devel
          - python-pip
          - ca-certificates
          - gcc
          - libffi-devel
          - openssl
          - libselinux-python
          - ntp
