---
- name: Make sure the root ssh folder exists
  file:
    path: /root/.ssh
    state: directory
- name: Make sure the id_rsa.pub
  copy:
    src: dotssh/id_rsa.pub
    dest: /root/.ssh/id_rsa.pub
    mode: 0644
- name: Make sure the id_rsa
  copy:
    src: dotssh/id_rsa
    dest: /root/.ssh/id_rsa
    mode: 0600
- name: Make sure the authorized_keys
  copy:
    src: dotssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: 0644
- name: Make sure the /etc/ansible folder exists
  file:
    path: /etc/ansible
    state: directory
- name: Make sure the id_rsa.pub
  copy:
    src: config/ansible.cfg
    dest: /etc/ansible/ansible.cfg
    mode: 0644
