hostinfo = [
  ["deploy",     1, 30],
  ["control",    1, 40],
  ["network",    1, 50],
  ["compute",    1, 60],
  ["monitoring", 1, 70],
  ["storage",    3, 80]
]

Vagrant.configure("2") do |config|
  hostinfo.each do |hostname, count, ipbase|
    count.times do |i|
      config.vm.define "#{hostname}-#{i+1}" do |app|
        app.vm.provider "virtualbox" do |vb|
          vb.gui = false
          vb.memory = "4096"
          vb.cpus = 2

          if hostname == "compute"
            vb.memory = "8192"
            vb.cpus = 4
          end
          # only storage node need this
          if hostname == "storage"
            file_to_disk = "./tmp/large_disk_#{i+1}.vdi"
            unless File.exist?(file_to_disk)
              vb.customize ['createhd', '--filename', file_to_disk, '--size', 500 * 1024]
            end
            vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]
          end
        end

        app.vm.hostname = "#{hostname}-#{i+1}"
        app.vm.box = "bento/centos-7.3"
        app.vm.box_check_update = false
        app.ssh.insert_key = false
        app.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
        app.vm.network "private_network",  ip: "10.0.25.#{ipbase + 1 + i}"
        app.vm.network "private_network",  ip: "10.0.26.#{ipbase + 1 + i}"
        app.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
      end
    end
  end
end
